### ISSUE TITLE
Bug: Connection to MongoDB failed

### ISSUE THREAD

**Issue by 1407arjun** [1407arjun/DBKong#2]
There seems to be a bug due to which connection to MongoDB cannot be established. All the **GET/POST** requests are hitting the server but I don't seem to get a response or sometimes I get a response with a **500 error**. Any help will be appreciated.

**Comment by Tanmay000009** [comment]
Hey, can you please send the path where NodeJS files are located?

**Comment by 1407arjun** [comment]
Its located at [`app/src/main/assets/nodejs`](../tree/master/app/src/main/assets/nodejs).

**Comment by Tanmay000009** [comment]
Sure, will take a look.

**Comment by Tanmay000009** [comment]
Seems to be an issue with URI mostly, have faced a kinda similar issue. Can you please assign me this issue?
Also, can you please send the path of files from where you are sending URI? And a brief description of how it is being sent from user on mobile to server.

**Comment by 1407arjun** [comment]
The class hierarchy is as follows (from super class to inherited class): `DBKong` > `MongoDBDao` > `Collection` > `Database` > `MongoDBConnect`. The app makes a **POST** request to the server, the code for which is present in `Volley.java`.

**Comment by 1407arjun** [comment]
@Tanmay000009 I'm assigning this issue to you.
